### ISSUE TITLE
NullPointerException in MobicomLocationActivity

### ISSUE THREAD

**Issue by Amagi82** [AppLozic/Applozic-Android-SDK#259] opened 2017-06-22 18:39 UTC
Device: LGMS330
Android Api 22
Applozic v4.85

> Exception java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
com.applozic.mobicomkit.uiwidgets.conversation.activity.MobicomLocationActivity$1.onClick (MobicomLocationActivity.java:119)
android.view.View.performClick (View.java:4799)
android.view.View$PerformClick.run (View.java:20042)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5422)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:914)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:707)

**Comment by Sunilkumarr** [comment] 2017-06-22 19:15
@Amagi82  Is this happening in any specific case ?

**Comment by Amagi82** [comment] 2017-06-22 20:38
This happens whenever you try to share your location if LocationServices is unable to find the last known location. Check here, inside [MobicomLocationActivity](https://github.com/AppLozic/Applozic-Android-SDK/blob/db3d7d237cb059895e777ecdd4c05d2bef814270/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/MobicomLocationActivity.java):

`    @Override
    public void onConnected(Bundle bundle) {
        try {
            if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED && ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
                // TODO: Consider calling
                //    ActivityCompat#requestPermissions
                // here to request the missing permissions, and then overriding
                //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                //                                          int[] grantResults)
                // to handle the case where the user grants the permission. See the documentation
                // for ActivityCompat#requestPermissions for more details.
                return;
            }
            mCurrentLocation = LocationServices.FusedLocationApi.getLastLocation(googleApiClient);
            if (mCurrentLocation == null) {
                Toast.makeText(this, R.string.waiting_for_current_location, Toast.LENGTH_SHORT).show();
                locationRequest = new LocationRequest();
                locationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
                locationRequest.setInterval(UPDATE_INTERVAL);
                locationRequest.setFastestInterval(FASTEST_INTERVAL);
                LocationServices.FusedLocationApi.requestLocationUpdates(googleApiClient, locationRequest, this);
            }

            if (mCurrentLocation != null)
                mapFragment.getMapAsync(this);

        } catch (Exception e) {
        }

    }`

Looking at this code, there is absolutely no guarantee mCurrentLocation will be non-null. You're not even handling the exception in your try-catch. And then you call mCurrentLocation throughout that class without null checking. Those are some extremely risky coding practices.

**Comment by Sunilkumarr** [comment] 2017-06-23 09:08
Thanks for pointing it out we will root cause this issue

**Comment by Sunilkumarr** [comment] 2017-06-29 09:33
This has been fixed in `compile 'com.applozic.communication.uiwidget:mobicomkitui:4.88'` you can try with this gradle version

**Closed by Sunilkumarr** 2017-06-29 09:33 UTC
