### ISSUE TITLE
No virtual method addOnTabSelectedListener after updating to androidx dependencies

### ISSUE THREAD

**Issue by Amagi82** [AppLozic/Applozic-Android-SDK#352] opened 2018-10-18 21:01 UTC
## Actual Results

After we updated to the new AndroidX/JetPack dependencies, when clicking on the button to create a new conversation, Applozic crashes with the following:

```
<package name> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <package name>, PID: 17379
    java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Lcom/google/android/material/tabs/TabLayout$OnTabSelectedListener;)V in class Lcom/google/android/material/tabs/TabLayout; or its super classes (declaration of 'com.google.android.material.tabs.TabLayout' appears in /data/app/<package name>-7Wr7zPJfX8kZ18Ue_XM35w==/base.apk)
        at com.applozic.mobicomkit.uiwidgets.people.activity.MobiComKitPeopleActivity.onCreate(MobiComKitPeopleActivity.java:167)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## Steps to Reproduce
1. Use Androidx dependencies + Applozic in a sample project with compileSdkVersion 28
2. Launch Applozic
3. Click the floating action button to start a new conversation and it will crash immediately

Applozic Android SDK version: 5.10
Android device: Pixel 2 XL
Android OS version: 9.0 / Pie
Dependencies used with version: 
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.71"
    implementation "androidx.appcompat:appcompat:1.0.0"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation 'androidx.collection:collection-ktx:1.0.0'
    implementation "androidx.constraintlayout:constraintlayout:2.0.0-alpha2"
    implementation "androidx.core:core-ktx:1.0.0"
    implementation "androidx.exifinterface:exifinterface:1.0.0"
    implementation 'androidx.fragment:fragment-ktx:1.0.0'
    implementation "androidx.lifecycle:lifecycle-common-java8:2.0.0"
    implementation "androidx.lifecycle:lifecycle-extensions:2.0.0"
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:2.0.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0"
    implementation "androidx.recyclerview:recyclerview:1.0.0"
    implementation "androidx.room:room-runtime:2.0.0"
    implementation "androidx.room:room-rxjava2:2.0.0"
    implementation "androidx.transition:transition:1.0.0"
    implementation "com.bluelinelabs:conductor:2.1.5"
    implementation "com.google.android:flexbox:1.0.0"
    implementation "com.google.android.gms:play-services-base:16.0.1"
    implementation "com.google.android.gms:play-services-location:16.0.0"
    implementation "com.google.android.gms:play-services-maps:16.0.0"
    implementation "com.google.android.material:material:1.0.0"
    implementation "com.google.code.gson:gson:2.8.5"
    implementation "com.google.firebase:firebase-appindexing:16.0.2"
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-config:16.0.1"
    implementation "com.google.firebase:firebase-messaging:17.3.3"
    implementation "com.google.firebase:firebase-perf:16.1.2"
    implementation "com.isseiaoki:simplecropview:1.1.7"
    implementation "com.squareup.okhttp3:okhttp:3.11.0"
    implementation "com.squareup.okhttp3:logging-interceptor:3.11.0"
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation "com.squareup.retrofit2:retrofit:2.4.0"
    implementation "com.squareup.retrofit2:converter-gson:2.4.0"
    implementation "com.squareup.retrofit2:converter-scalars:2.4.0"
    implementation "io.reactivex.rxjava2:rxjava:2.2.0"
    implementation "io.reactivex.rxjava2:rxkotlin:2.3.0"
    implementation "io.reactivex.rxjava2:rxandroid:2.0.2"
    implementation "com.applozic.communication.uiwidget:mobicomkitui:5.10"
    implementation("com.crashlytics.sdk.android:crashlytics:2.9.5@aar") { transitive = true }
    implementation('io.branch.sdk.android:library:2.19.3@aar') { transitive = true }
    implementation "io.intercom.android:intercom-sdk-base-transitive:5.1.4"
    implementation("io.intercom.android:intercom-sdk-fcm:5.1.4") { exclude group: 'io.intercom.android', module: 'intercom-sdk-base' }
    betaImplementation 'com.bugsee:bugsee-android:1.12.14'
    androidTestImplementation "org.jetbrains.kotlin:kotlin-test-junit:1.2.71"
    androidTestImplementation "androidx.annotation:annotation:1.0.0"
    androidTestImplementation "androidx.arch.core:core-testing:2.0.0"
    androidTestImplementation "androidx.room:room-testing:2.0.0"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.1.0-beta02"
    androidTestImplementation 'androidx.test:rules:1.1.0-beta02'
    androidTestImplementation "androidx.test:runner:1.1.0-beta02"
    androidTestImplementation "com.google.code.findbugs:jsr305:3.0.2"
    androidTestImplementation "org.amshove.kluent:kluent-android:1.40"
    androidTestImplementation "org.mockito:mockito-android:2.21.0"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:1.2.71"
    testImplementation "androidx.arch.core:core-testing:2.0.0"
    testImplementation "org.amshove.kluent:kluent-android:1.40"
    testImplementation "org.mockito:mockito-inline:2.21.0"
    testImplementation "junit:junit:4.12"
    kapt "androidx.room:room-compiler:2.0.0"
}
```

**Comment by aditrioka** [comment] 2018-11-19 11:03
I have the similar issue, is there any update for this problem?

**Comment by Sunilkumarr** [comment] 2018-11-20 10:38
@Amagi82 @aditrioka  Do you have any sample project where we can reproduce this issue Can you share the link for it?

**Comment by aditrioka** [comment] 2018-11-28 02:58
> @aditrioka Migrating support library to new androidX library might take some time as we have other library which we are using internally.
> 
> We are trying to update the sdk to 28.0.0 support library and android 9 support will keep update once we are done with changes
> 
> we will check if support library androidx in app build.gradle and by upgrading our SDK support library to 28.0.0 might solve that crash or else you need to downgrade your androidx to support library to 28.0.0.

downgrade to 28.0.0? So currently we're not yet be able to use androidx? please inform me in the future if using androidx is working. Thanks @Sunilkumarr, you guys awesome!

**Comment by Sunilkumarr** [comment] 2018-12-10 10:34
@aditrioka Yes. For now you can downgrade your app all support library  to 28.0.0  we have released with support library 28.0.0. You cant use both androix and 28.0.0  you may get conficts in support library

**Comment by aditrioka** [comment] 2018-12-12 07:32
okay, thank you @Sunilkumarr . Looking forward for using androidx with applozic, because google said next year they will drop all the support library and will only support androidx. :)

**Closed** 2019-04-11 11:42 UTC

**Comment by Sunilkumarr** [comment] 2019-09-05 15:42
@aditrioka @Amagi82   You can use the latest version we added support for androidX doc link https://docs.applozic.com/docs/android-chat-sdk#section-gradle-dependency

**Comment by waheedakhter** [comment] 2019-10-03 14:51
I am getting the same error in react-native version. haven't you updated that with respect to androidx?
